---
title: Feedbakly - Blog
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
baseurl: ''
subtitle: The easiest way to give feedback
author: feedbakly
simple_search: http://google.com/search
description: A blog on giving and receiving feedback
name: feedbakly
markdown: kramdown
markdown_ext: markdown,mkdown,mkdn,mkd,md
permalink: "/:short_year/:title"
excerpt_separator: "<!--more-->"
exclude:
- Gemfile
- Gemfile.lock
- Rakefile
- UploadToGithub.Rakefile
- README.md
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
